"""empty message

Revision ID: f56f0b639a0c
Revises: 3ee16cfe827c
Create Date: 2024-09-13 08:02:16.631909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56f0b639a0c'
down_revision = '3ee16cfe827c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekday_request', sa.Boolean(), nullable=False,server_default=sa.text('false')))
        batch_op.add_column(sa.Column('weekend_request', sa.Boolean(), nullable=False,server_default=sa.text('false')))
        batch_op.add_column(sa.Column('weekday_teetimes', sa.Boolean(), nullable=False,server_default=sa.text('false')))
        batch_op.add_column(sa.Column('weekend_teetimes', sa.Boolean(), nullable=False,server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.drop_column('weekend_teetimes')
        batch_op.drop_column('weekday_teetimes')
        batch_op.drop_column('weekend_request')
        batch_op.drop_column('weekday_request')

    # ### end Alembic commands ###
